In [4]:
def mark_grade(score):
    if score >= 90:
        grade="A"
        grade_score=90
    elif score >= 80:
        grade="B"
        grade_score=80
    elif score >= 70:
        grade="C"
        grade_score=70
    elif score >= 60:
        grade="D"
        grade_score=60
    else :
        grade="E"
        grade_score=50
    return grade,grade_score
percentage_mark=int(input("Enter your percentage mark"))
grade1,grade_score1=mark_grade(percentage_mark)

#exam_grade=mark_grade(99)
print("Your Grade is ",grade1,grade_score1)

Your Grade is  A 90


In [6]:
target_grade=input("Enter target grade")
print("Your target grade --",target_grade)

if target_grade=="A":
    target_no=90
elif target_grade=="B":
    target_no=80
elif target_grade=="c":
    target_no=70

#print("sas",target_no)

if target_no>grade_score1:
    print("Your grade is ",grade1,"COMMENT:   Need Improvement")
elif target_no == grade_score1:
    print("Your grade is ",grade1,": COMMENT:    reached your target")
elif target_no < grade_score1:
    print("Your grade is ",grade1,"COMMENT:            good")



Your target grade -- A
Your grade is  A COMMENT:    reached your target


In [16]:
my_file = open("Numbers.txt", "w")

for i in range(4):
    my_file.write(input("Enter Four Numbers"))
    my_file.write("\n")

my_file.close()

In [17]:
with open("Numbers.txt", "r") as myfile:
    data = myfile.read()

myfile.close()

print(data)

22
33
44
55



In [18]:

# Appending
my_file = open("Numbers.txt", "a")

my_file.write(input("Enter  Number"))
my_file.write("\n")

my_file.close()


In [19]:
with open("Numbers.txt", "r") as myfile:
    data = myfile.read()

myfile.close()

print(data)

22
33
44
55
888888



In [24]:
import numpy as np
array = np.array([0,1, 2, 3, 4, 5, 6, 7 ,8  ,9])

print(array)
# slices data from index 1 to 4  - 0 indexed and discounts final number

[0 1 2 3 4 5 6 7 8 9]


In [30]:
bool_type=np.ones((3,3), dtype=bool)

print(bool_type)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]


array([1, 3, 5, 7, 9])

In [35]:
import numpy as np

array = np.arange(10)    # dummy array

result = []    # a seperate list for storing odd numbers

for i in array:

 if i % 2 != 0:

   result.append(i)

print(np.array(result)) 

[1 3 5 7 9]


In [45]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]


array([1, 3, 5, 7, 9])